version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"

registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org/
    username: ${{ github.repository_owner }}
    password: ${{ secrets.NPM_TOKEN }}
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com/
    token: ${{ secrets.GITHUB_TOKEN }}
    replaces-base: true
