compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - windows
  cpu:
    - current
    - x64
    - arm64

npmRegistries:
  //npm.pkg.github.com/: 
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
  //registry.npmjs.org/: 
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
npmScopes:
  ralphschuler:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
