compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - windows
  cpu:
    - current
    - x64
    - arm64
