name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: [feature]
assignees:
  - ralphschuler
body:
  - type: markdown
    attributes:
      value: "## Thank you for contributing to our project!"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: Please describe your idea in detail.
      placeholder: Tell us what you dream of
      value: "When playing the game i want it to ..."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request.
