name: Close Issue

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: number

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Close Issue
        run: gh issue close ${{ inputs.issue_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
