name: List Packages

on:
  workflow_call:
    outputs:
      packages:
        description: "List of packages"
        value: ${{ jobs.list-packages.outputs.packages }}

jobs:
  list-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.list-packages.outputs.packages }}

    steps:
      - uses: actions/checkout@v4

      - id: list-packages
        run: |
          packages=$(find packages/ -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')
          echo "packages=${packages}" >> ${GITHUB_OUTPUT}
