name: Unpublish Git NPM Package

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      package_name:
        required: true
        type: string

jobs:
  unpublish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - name: Unpublish Package
        run: npm unpublish @ralphschuler/${{ inputs.package_name }} --force
