name: Build Actions

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        action: [ collect-files, merge-eslint-reports ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Navigate to action
        run: cd ./.github/actions/${{ matrix.action }}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
