name: Collect Files

on:
  workflow_call:
    inputs:
      pattern:
        type: string
        description: 'Glob pattern to match files against'
        required: true
      target:
        type: string
        description: 'Target directory to copy files to'
        required: false
    outputs:
      target:
        description: 'Target directory to copy files to'
        value: ${{ jobs.collect.outputs.target }}

jobs:
  collect:
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.set_output.outputs.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7.0.1
        id: collect_files
        env:
          INPUT_PATTERN: ${{ github.event.inputs.pattern }}
          INPUT_TARGET: ${{ github.event.inputs.target }}
        with:
          script: |
            const glob = require('glob');
            const fs = require('fs');
            const path = require('path');
            
            const GREEN = '\x1b[32m%s\x1b[0m';
            
            async function collectFiles({pattern, target}) {
              if (!pattern || !target) throw new Error('Missing either pattern or target params');
            
              console.log(GREEN, `Collecting files... into ${target}`);
            
              glob(pattern, {}, (err, files) => {
                  if (err) throw err;
                  files.forEach((file, index) => {
                      fs.copyFileSync(file, path.resolve(target, `${index}-${path.basename(file)}`));
                  });
              });
            
              console.log(GREEN, `Done.`);
              return target;
            }
            
            return collectFiles({
              pattern: process.env.INPUT_PATTERN,
              target: process.env.INPUT_TARGET || `./${Buffer.from(new Date().toISOString()).toString('base64')}`
            });
      - id: set_output
        run: echo "target=${TARGET}" >> $GITHUB_OUTPUT
        env:
          TARGET: ${{ steps.collect_files.outputs.result }}
