name: Collect Files

on:
  workflow_dispatch:
    inputs:
      pattern:
        description: 'Glob pattern to match files against'
        required: true
      target:
        description: 'Target directory to copy files to'
        required: true

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7.0.1
        env:
          INPUT_PATTERN: ${{ github.event.inputs.pattern }}
          INPUT_TARGET: ${{ github.event.inputs.target }}
        with:
          script: |
            const glob = require('glob');
            const fs = require('fs');
            const path = require('path');
            
            const GREEN = '\x1b[32m%s\x1b[0m';
            
            async function collectFiles({pattern, target}) {
              if (!pattern || !target) throw new Error('Missing either pattern or target params');
            
              console.log(GREEN, `Collecting files... into ${target}`);
            
              glob(pattern, {}, (err, files) => {
                  if (err) throw err;
                  files.forEach((file, index) => {
                      fs.copyFileSync(file, path.resolve(target, `${index}-${path.basename(file)}`));
                  });
              });
            
              console.log(GREEN, `Done.`);
            }
            
            collectFiles({
              pattern: process.env.INPUT_PATTERN,
              target: process.env.INPUT_TARGET
            });
          
