name: Create Issue Branch

on:
  issues:
    types: [opened]

jobs:
  create-issue-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Branch
        run: |
          issue_number=${{ github.event.issue.number }}
          git checkout -b issue-${issue_number}
          git push origin issue-${issue_number}
