name: List Updated Packages

on:
  workflow_call:
    inputs:
      fetch-depth:
        type: number
        description: 'Fetch depth for git checkout'
        required: true
        default: 2
    outputs:
      updated_packages:
        description: 'List of updated packages'
        value: ${{ jobs.list-updated-packages.outputs.updated_packages }}
jobs:
  list-updated-packages:
    runs-on: ubuntu-latest
    outputs:
      updated_packages: ${{ steps.determine-updated-packages.outputs.updated-packages }}

    steps:
      - name: List Changes
        id: list-changes
        uses: ./.github/workflows/list-changes.yml
        with:
          fetch-depth: 2

      - name: List Packages
        id: list-packages
        uses: ./.github/workflows/list-packages.yml

      - name: Determine Updated Packages
        id: determine-updated-packages
        run: |
          # Script to determine updated packages using outputs from list-changes and list-packages
          updated_packages=()
          for package in ${{ steps.list-packages.outputs.packages }}; do
            for directory in ${{ steps.list-changes.outputs.directories }}; do
              if [[ "$directory" == "packages/$package" ]]; then
                updated_packages+=("$package")
                break
              fi
            done
          done
          echo "updated_packages=$(printf '%s\n' "${updated_packages[@]}" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
