name: Merge ESLint reports

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target output file"
        required: false
        default: "./eslint_report.json"

jobs:
  merge-eslint-reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p ./.eslint_reports/
      - uses: "./.github/workflows/collect-files.yml"
        with:
          pattern: "**/eslint_report.json"
          target: "./.eslint_reports/"
      - uses: actions/github-script@v7.0.1
        env:
          target: ${{ github.event.inputs.target }}
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const directory = path.join(__dirname, 'eslint_reports');
            const files = fs.readdirSync(directory);
            const annotations = files.reduce((acc, file) => {
              const rawReport = require(path.join(directory, file));
              const parsedReport = JSON.parse(rawReport);
              return [
                ...acc,
                ...parsedReport
              ];
            }, []);

            fs.writeFileSync(target, JSON.stringify(annotations, null, 2));
