name: Node.js Package Workflow

on:
  push:
    branches:
      - main
  release:
    types: [created]

env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NODE_VERSION: 20

jobs:
  format-and-lint:
    name: Format and lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "yarn"
      - run: corepack enable
      - run: yarn  install
      - run: yarn  format
      - run: yarn  lint

  build-and-test:
    name: Build and test
    needs: format-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "yarn"
      - run: corepack enable
      - run: yarn  install
      - run: yarn  build
      - run: yarn  test

  publish:
    name: Publish
    needs: build-and-test
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://npm.pkg.github.com/
          cache: "yarn"
      - run: corepack enable
      - run: yarn  install
      - run: yarn  publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
