name: Pull Request

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - run: corepack enable
      - run: yarn
      - run: yarn lint:report
        continue-on-error: true
      - run: mkdir -p eslint_reports
      - name: Collect Reports
        uses: ./.github/actions/collect-files
        with:
          pattern: "**/eslint_report.json"
          output_directory: "eslint_reports/"
      - uses: ./.github/actions/merge-eslint-reports
        with:
          input_directory: "eslint_reports/"
          output_file: "eslint_report.json"
      - uses: ataylorme/eslint-annotate-action@v2
        with:
          report-json: "eslint_report.json"

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - run: corepack enable
      - run: yarn
      - run: yarn test
      # - run: mkdir -p test_reports
      # - name: Collect Reports
      #   uses: ./.github/actions/collect-files
      #   with:
      #     pattern: "**/test_report.json"
      #     target_directory: "test_reports/"
      # - uses: ./.github/actions/merge-test-reports
      #   with:
      #     input_directory: "test_reports/"
      #     output_file: "test_report.json"
      # - uses: ataylorme/test-annotate-action@v2
      #   with:
      #     report-json: "test_report.json"

  format:
    if: ${{ github.event.pull_request.merged == true }}
    name: Format
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - run: corepack enable
      - run: yarn
      - run: yarn format:fix
      - run: |
          git config --global user.name '${{ github.pull_request.user.login }}'
          git config --global user.email '${{ github.pull_request.user.email }}'
          git add .
          git commit -m "chore: format code"
          git push
