name: Pull Request

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - run: corepack enable
      - run: yarn
      - run: yarn lint:report
        continue-on-error: true
      - uses: "./.github/workflows/merge-eslint-reports.yml"
        with:
          target: "eslint_report.json"
      - uses: ataylorme/eslint-annotate-action@v2
        with:
          report-json: "eslint_report.json"

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - run: corepack enable
      - run: yarn
      - run: yarn test
      # - run: mkdir -p test_reports
      # - name: Collect Reports
      #   uses: "./.github/actions/collect-files.yml"
      #   with:
      #     pattern: "**/test_report.json"
      #     target: "test_reports/"

  format:
    if: ${{ github.event.pull_request.merged == true }}
    name: Format
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - run: corepack enable
      - run: yarn
      - run: yarn format:fix
      - run: |
          git config --global user.name '${{ github.pull_request.user.login }}'
          git config --global user.email '${{ github.pull_request.user.email }}'
          git add .
          git commit -m "chore: format code"
          git push
