name: Release

on:
  release:
    types: [created, deleted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: ${{ github.event.action == 'created' }}
    name: Publish to ${{ matrix.registry }}
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ matrix.auth-token }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - registry: npm
            registry-url: https://registry.npmjs.org/
            auth-token: ${{ secrets.NPM_TOKEN }}
            scope: ''
          - registry: gpr
            registry-url: https://npm.pkg.github.com/
            auth-token: ${{ secrets.GITHUB_TOKEN }}
            scope: '@${{ github.repository_owner }}'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - run: corepack enable
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      # - uses: actions/cache@v3
      #   id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn publish

  unpublish:
    if: ${{ github.event.action == 'deleted' }}
    name: Unpublish from ${{ matrix.registry }}
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ matrix.auth-token }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - registry: npm
            registry-url: https://registry.npmjs.org/
            auth-token: ${{ secrets.NPM_TOKEN }}
            scope: ''
          - registry: gpr
            registry-url: https://npm.pkg.github.com/
            auth-token: ${{ secrets.GITHUB_TOKEN }}
            scope: '@${{ github.repository_owner }}'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - run: corepack enable
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      # - uses: actions/cache@v3
      #   id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn unpublish --force
