triggers:
  - branch_name: main
    run:
      workflow: generate_readme_summaries
      parameters:
        FILE_SUMMARY_PROMPT: "Write an executive summary of this file, intended for someone seeing it for the first time. Write 3-6 bullet points, prefixed with emojis."
        FILE_SUMMARY_INSTRUCTIONS: "Respond in 3-6 bullet points, using plenty of emojis."
        FOLDER_SUMMARY_PROMPT: "Write an executive summary of this folder, intended for someone seeing it for the first time. Respond in 3-5 sentences."
        FOLDER_SUMMARY_INSTRUCTIONS: "Respond in simple sentences, using plenty of emojis."
        IGNORE_FILES:
          - docs
        EMPTY_FILE_SUMMARY: "This file is empty."

  - branch_name: main
    run:
      workflow: publish_todo_issues
      parameters:
        ISSUE_LABEL_CHOICES:
          - "easy"
          - "medium"
          - "hard"
        ISSUE_LABEL_PROMPT: |
          How hard is this task?
        ISSUE_DESCRIPTION_PROMPT: |
          What tips can you give to someone that's resolving this TODO?
        ISSUE_DESCRIPTION_INSTRUCTIONS: |
          Respond in 1-3 sentences.

  - type: label
    label_substring: summarize
    on_pull_request: true
    workflow: summarize_pr
